### ISSUE TITLE
Deleted matrix blocks on hide

### ISSUE THREAD

**Issue by herrajon** [lindseydiloreto/craft-matrixcolors#12]
Howdy

Thank you for your excellent plugin.

Recently stumbled on a bug which might be caused by Matrix Colors.

I am using Craft CMS 2.6.3019 and Matrix Colors 1.1.3. International Locale (Icelandic).

The Problem: When editing entries and attempting to 'hide' matrix blocks the matrix blocks disappears (deletes).

First I thought it was a Craft CMS bug but by chance I found out that if I removed old definitions in Matrix Colors (for blocktypes that have been deleted) then the problem goes away and the 'deleted' matrix blocks reappear.

Everything works dandy when using the vanilla locale (en_US).

**Comment by lindseydiloreto** [comment]
Strange, thanks for reporting that.

I'll take a look when I get a chance, and report back on what I find. 👍

**Comment by lindseydiloreto** [comment]
Well I never looked into this, but also I never heard of any similar reports. It seems like this was an isolated incident.

And in the meantime, both Craft and Matrix Colors have evolved significantly since you first posted this. Which means there's nothing left to do except close this thread.

Thanks for reporting the issue, sorry for never figuring out the culprit! 🙂

**Comment by herrajon** [comment]
thx for the reply.

Keep on the good work.

Cheers 

HJ
